---
title: "Osa Conservation: Talamanca Conservation Campus"
author:
  - Osa Conservation
site: bookdown::test-bookdown
output: bookdown::gitbook
date: '`r paste("Updated on", Sys.Date())`'
documentclass: book
biblio-style: apalike
link-citations: yes
editor_options: 
  chunk_output_type: console
---

# Introduction

```{r c01, echo=F, message=F, include=F}
knitr::opts_chunk$set(echo = FALSE, message=F, warning=F)

library(dplyr)
library(leaflet)
library(units)
library(sf)
library(viridis)
library(kableExtra)
library(lubridate)
library(plotly)
library(googledrive)
library(purrr)
library(readxl)
library(leaflet.extras)
library(tidyr)

#drive_auth()
googledrive::drive_auth(path = Sys.getenv("GOOGLE_AUTHENTICATION_CREDENTIALS"))
data_path <- "data"
dir.create(data_path) 
#test2
# For when the trapping effort file is sorted
# googledrive::drive_auth(path = Sys.getenv("GOOGLE_AUTHENTICATION_CREDENTIALS"))
# 
```


The following represents an interactive map of the developments at the Talamanca Conservation Campus. 

```{r, c02, include=F, message=F, warning=F, results="hide"}
#Import the shapefiles for the maps

dir.create("shapefiles")
shp_folder <- drive_ls(path = as_id("1hAAzibtvpKzUUOSNuI6hFZQUYydsBBuN"), recursive=T)

for(i in 1:nrow(shp_folder))
{
  # if it has a file extension download it
  if(substr(shp_folder$name[i], (nchar(shp_folder$name[i]) - 3),(nchar(shp_folder$name[i]) - 3))==".")
  {
  drive_download(file = as_id(shp_folder$id[i]), path = paste0("shapefiles/", shp_folder$name[i]), overwrite = TRUE)
  }
}

parcel <- st_read("shapefiles/shape pittier.shp")
parcel<- st_zm(parcel, drop = TRUE, what = "ZM")
parcel <- st_transform(parcel, 4326)
parcel$
```


```{r map4, echo=F, class.source="Rmain"}

m <- leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%  
  addTiles(group="Base") %>%     # Include a basemap option too
  addPolygons(data=parcel, group="property_boundary",
              weight=3) %>% 
  addLayersControl(
                    baseGroups = c("Satellite","Base"),
                    overlayGroups = c("property_boundary"),
                    options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl()

m

```

