name: scheduleRenderbook
on:     
  push:
  schedule:     
     - cron: "15 8 * * *"  


jobs:
  bookdown:
    name: Render-Book
    runs-on:   macos-latest # ubuntu-latest #  macos USES 10 TIMES THE MINUTES
    steps:
      - uses: actions/checkout@v2
      # More detail here, https://github.com/r-lib/actions
      # It's possible to define R and pandoc version if desired
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Install units
        run: Rscript -e "install.packages('units')"
      - name: Install leaflet
        run: Rscript -e "install.packages('leaflet')"
      - name: Install dplyr
        run: Rscript -e "install.packages('dplyr')"
      - name: Install sf
        run: Rscript -e "install.packages('sf')"
      - name: Install viridis
        run: Rscript -e "install.packages('viridis')"
      - name: Install kableExtra
        run: Rscript -e "install.packages('kableExtra')"
      - name: Install lubridate
        run: Rscript -e "install.packages('lubridate')"
      - name: Install plotly
        run: Rscript -e "install.packages('plotly')"
      - name: Install googledrive
        run: Rscript -e "install.packages('googledrive')"
      - name: Install purrr
        run: Rscript -e "install.packages('purrr')"
      - name: Install readxl
        run: Rscript -e "install.packages('readxl')"
      - name: Install foreach
        run: Rscript -e "install.packages('foreach')"
      - name: Install leaflet.extras
        run: Rscript -e "install.packages('leaflet.extras')"

      - name: Render Book
        env: 
          GOOGLE_AUTHENTICATION_CREDENTIALS: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS }}
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v4
        with:
          name: _book
          path: _book/
  
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Download artifact
       uses: actions/download-artifact@v4
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
        build_dir: _book
        branch: gh-pages
